apiVersion: v2
name: external-dns
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.9.0
dependencies:
- name: external-dns
  version: 1.9.0
  repository: https://kubernetes-sigs.github.io/external-dns/
