apiVersion: v2
name: nextcloud
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: 3.0.3
dependencies:
- name: nextcloud
  version: 3.0.3
  repository: https://nextcloud.github.io/helm/
